--- ENVIRNOMENT CONFIGURATION FILE

common:
  database:
    host: localhost
    name: foo

  debug:
    mode: false

dev:
  database:
    user: john
    password: doe

  debug:
    mode: true

  cms:
    hostname: example.com

staging:

production: