--- ENVIRNOMENT CONFIGURATION FILE

# Common base for every environment
common:
  database:
    host: localhost
    name: foo_bar

  debug:
    mode: false

  cms:
    views:
      rootFolder: /src/views

dev:
  database:
    user: john
    password: doe

  debug:
    mode: true

  cms:
    hostname: example.com


# Other ENVS, for example
staging:
production:
